CREATE TABLE session_parms (sid TEXT, key TEXT, value TEXT, mtime NUMERIC, UNIQUE (sid, key) ON CONFLICT REPLACE);
CREATE TABLE users (object_id NUMERIC REFERENCES objects(id) ON UPDATE CASCADE ON DELETE CASCADE, nick TEXT UNIQUE, email TEXT, fullname TEXT, password TEXT);
CREATE TABLE text (object_id NUMERIC REFERENCES objects(id) ON UPDATE CASCADE ON DELETE CASCADE, data TEXT);
CREATE TABLE membership (parent_id NUMERIC REFERENCES objects(id) ON UPDATE CASCADE ON DELETE CASCADE, child_id NUMERIC REFERENCES objects(id) ON UPDATE CASCADE ON DELETE CASCADE);
CREATE TABLE objects (id INTEGER PRIMARY KEY, type TEXT, read NUMERIC, write NUMERIC, sequence NUMERIC, mtime NUMERIC);

